trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_toolchain: nightly

pool:
  vmImage: "ubuntu-16.04"

steps:
  - template: "_build/install-rust.yml"
    inputs:
      rustup_toolchain: $RUSTUP_TOOLCHAIN
  - template: "_build/cargo-build-and-test.yml"
    inputs:
      release: no
