trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_toolchain: nightly

variables:
  build_name: "$(Build.SourceBranchName)"
  is_tag: "${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}"

pool:
  vmImage: "ubuntu-16.04"

steps:
  - template: ".build/install-rust.yml"
  - template: ".build/cargo-build-and-test.yml"
  - template: ".build/publish-crate.yml"
