routes:
  - pattern: "^/test$"
    methods:
      - get
    downstream:
      base_url: "http://postman-echo.com"
      path: "/get?foo1=bar1"
  - pattern: "^/test/post$"
    methods:
      - post
    downstream:
      base_url: "http://postman-echo.com"
      path: "/get?foo1=bar1"
listener:
  interface: "0.0.0.0:8000"
