routes:
  - pattern: "^/test/(?P<cap>.*)$"
    methods:
      - get
    downstream:
      base_url: "http://postman-echo.com"
      path: "/get?env_user={{env=>USER}}&regex_cap={{regex=>cap}}"
  - pattern: "^/test/post$"
    methods:
      - post
    downstream:
      base_url: "http://postman-echo.com"
      path: "/get?foo1=bar"
listener:
  interface: "0.0.0.0:8000"
