listener:
  interface: "0.0.0.0:8000"

hosts:
  nginx:
    balancer: round_robin
    servers:
      - "http://localhost:9999"
  echo:
    balancer: least_connection
    servers:
      - "https://postman-echo.com"
      - "https://postman-echo.com"

routes:
  - pattern: "^/$"
    methods:
      - get
    handler:
      type: host
      host: nginx
      path: "/"

  - pattern: "^/test/(?P<cap>.*)$"
    methods:
      - get
    handler:
      type: host
      host: echo
      path: "/get"
      query:
        regex_cap: '{{ http.matched("cap") }}'
        method: "{{ http.method() }}"
        ip: "{{ http.ip() }}"
      headers:
        header: '{{ http.header("user-agent") }}'
        claim: '{{ auth.claim("KatalystAuthenticator") }}'
    authenticators:
      - backend: http
        url: "https://postman-echo.com/get?thing=something"

  - pattern: "^/test/post$"
    methods:
      - post
    handler:
      type: host
      host: echo
      path: "foo1=bar"
    authenticators:
      - backend: never
