---
service:
  interfaces:
    - address: "0.0.0.0:5010"
  cache:
    type: memory_cache

hosts:
  local:
    type: round_robin
    servers:
      - "http://localhost"

routes:
  - path:
      type: regex
      pattern: "^/$"
    handler:
      type: hello_world
