listener:
  interface: "0.0.0.0:8000"

hosts:
  echo:
    balancer: least_connection
    servers:
      - "https://postman-echo.com/get?host=host1&"
      - "https://postman-echo.com/get?host=host2&"

routes:
  - pattern: "^/test/(?P<cap>.*)$"
    methods:
      - get
    downstream:
      host: echo
      path: "env_user={{env=>USER}}&regex_cap={{regex=>cap}}&method={{http=>method}}&ip={{http=>ip}}&header={{header=>user-agent}}&claim={{claim=>KatalystAuthenticator}}"
    authenticators:
      - backend: http
        url: "https://postman-echo.com/get?thing=something"

  - pattern: "^/test/post$"
    methods:
      - post
    downstream:
      host: echo
      path: "foo1=bar"
    authenticators:
      - backend: never
