listener:
  interface: "0.0.0.0:8000"

hosts:
  nginx:
    balancer: round_robin
    servers:
      - "http://localhost:9999"
  echo:
    balancer: least_connection
    servers:
      - "https://postman-echo.com"
      - "https://postman-echo.com"

routes:
  - pattern: "^/$"
    methods:
      - get
    downstream:
      host: nginx
      path: "/"

  - pattern: "^/test/(?P<cap>.*)$"
    methods:
      - get
    downstream:
      host: echo
      path: "/get"
      query:
        regex_cap: "{{regex=>cap}}"
        method: "{{http=>method}}"
        ip: "{{http=>ip}}"
      headers:
        header: "{{header=>user-agent}}"
        claim: "{{claim=>KatalystAuthenticator}}"
    authenticators:
      - backend: http
        url: "https://postman-echo.com/get?thing=something"

  - pattern: "^/test/post$"
    methods:
      - post
    downstream:
      host: echo
      path: "foo1=bar"
    authenticators:
      - backend: never
