version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 9999:80
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    logging:
      driver: none
  katalyst:
    build: "../../."
    links:
      - "nginx:web"
    volumes:
      - "./katalyst.yml:/katalyst.yml:ro"
    logging:
      driver: none
  load-test:
    build: .
    command: -c 500 -n 300000 -k -G 16 -r http://nginx/
    links:
      - "nginx:nginx"
      - "katalyst:katalyst"
