[tasks.deb]
description = "Create a debian package"
install_crate = "cargo-deb"
command = "cargo"
args = ["deb"]

[tasks.watch]
description = "Run the project, monitor for changes and rerun when changed"
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run -- -c ../assets/manual-test.yml"]

[tasks.build]
description = "Build the project"
command = "cargo"
args = ["build"]

[tasks.test]
description = "Run the unit tests"
command = "cargo"
args = ["test"]

[tasks.build-release]
description = "Build the project with optimizations"
command = "cargo"
args = ["build", "--release"]
